// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PyDjinni
{
    internal sealed partial class Vsix
    {
        public const string Id = "PyDjinni.11f7ab29-c8f8-4263-bab2-089234abd5df";
        public const string Name = "PyDjinni";
        public const string Description = @"PyDjinni Visual Studio Extension";
        public const string Language = "en-US";
        public const string Version = "0.0.0";
        public const string Author = "PyDjinni";
        public const string Tags = "";
    }
}
