<?xml version="1.0" encoding="utf-8"?>
<plist version="1.0">
    <dict>
        <key>$schema</key>
        <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
        <key>name</key>
        <string>PyDjinni</string>
		<key>fileTypes</key>
		<array>
		<string>pydjinni</string>
		</array>
        <key>scopeName</key>
        <string>text.pydjinni</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#comment</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#import</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#string</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#enum_modifiers</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#types</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#modifiers</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#deriving_targets</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename_reference_parameter</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename_reference_return</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename_reference_namespace</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename_reference_throws_1</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename_reference_throws_2</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename_reference_throws_3</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename_reference_throws_4</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename_reference_throws_5</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#typename_reference_throws_6</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#namespace_typename</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#parameter</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#interface_targets</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#punctuation_terminator</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#punctuation_block</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#punctuation_comma</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#punctuation_accessor</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#operator_assignment</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#operator_type_annotation</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#parentheses</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>comment</key>
            <dict>
                <key>name</key>
                <string>comment.line.hashtag</string>
                <key>begin</key>
                <string>#</string>
                <key>end</key>
                <string>$</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>storage.type.class</string>
                        <key>match</key>
                        <string>@returns|@deprecated</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(@param)\s*(\w+)?</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type.class</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>variable.other</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(@throws)\s*([\w.]+)?</string>
                        <key>captures</key>
                        <dict>
                            <key>1</key>
                            <dict>
                                <key>name</key>
                                <string>storage.type.class</string>
                            </dict>
                            <key>2</key>
                            <dict>
                                <key>name</key>
                                <string>variable.other</string>
                            </dict>
                        </dict>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>markup.inline.raw.string</string>
                        <key>match</key>
                        <string>`.*`</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>markup.bold</string>
                        <key>match</key>
                        <string>\*\*[^*]+\*\*</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>markup.italic</string>
                        <key>match</key>
                        <string>\*[^*]+\*</string>
                    </dict>
                </array>
            </dict>
            <key>import</key>
            <dict>
                <key>match</key>
                <string>@import|@extern</string>
                <key>name</key>
                <string>keyword.control.import</string>
            </dict>
            <key>string</key>
            <dict>
                <key>match</key>
                <string>".*"</string>
                <key>name</key>
                <string>string.quoted.double</string>
            </dict>
            <key>enum_modifiers</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=\=)\s*(all|none)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.tag</string>
                    </dict>
                </dict>
            </dict>
            <key>types</key>
            <dict>
                <key>name</key>
                <string>storage.type</string>
                <key>match</key>
                <string>
                    \b(interface|enum|record|flags|error|function|namespace)\b
                </string>
            </dict>
            <key>modifiers</key>
            <dict>
                <key>name</key>
                <string>storage.modifier</string>
                <key>match</key>
                <string>\b(const|static|async|throws|main)\b</string>
            </dict>
            <key>deriving_targets</key>
            <dict>
                <key>begin</key>
                <string>\b(deriving)\s*(\()</string>
                <key>beginCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>storage.modifier</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.parameters</string>
                    </dict>
                </dict>
                <key>end</key>
                <string>(\))</string>
                <key>endCaptures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.parameters</string>
                    </dict>
                </dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>entity.name.tag</string>
                        <key>match</key>
                        <string>\w+</string>
                    </dict>
                </array>
            </dict>
            <key>typename</key>
            <dict>
                <key>match</key>
                <string>([\w]+)\s*(?=\=)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type</string>
                    </dict>
                </dict>
            </dict>
            <key>typename_reference_parameter</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=:)\s*([&lt;&gt;\w]+)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.interface</string>
                    </dict>
                </dict>
            </dict>
            <key>typename_reference_return</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=-&gt;)\s*([&lt;&gt;\w]+)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.interface</string>
                    </dict>
                </dict>
            </dict>
            <key>typename_reference_namespace</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=\.)([&lt;&gt;\w]+)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.interface</string>
                    </dict>
                </dict>
            </dict>
            <key>typename_reference_throws_1</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=throws)\s*([&lt;&gt;\w]+)\s*(?=,|.)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.interface</string>
                    </dict>
                </dict>
            </dict>
            <key>typename_reference_throws_2</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=throws)\s*([&lt;&gt;\w]+)\s*(?=-&gt;)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.interface</string>
                    </dict>
                </dict>
            </dict>
            <key>typename_reference_throws_3</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=throws)\s*([&lt;&gt;\w]+)\s*(?=;)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.interface</string>
                    </dict>
                </dict>
            </dict>
            <key>typename_reference_throws_4</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=,)\s*([&lt;&gt;\w]+)\s*(?=,|.)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.interface</string>
                    </dict>
                </dict>
            </dict>
            <key>typename_reference_throws_5</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=,)\s*([&lt;&gt;\w]+)\s*(?=-&gt;)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.interface</string>
                    </dict>
                </dict>
            </dict>
            <key>typename_reference_throws_6</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=,)\s*([&lt;&gt;\w]+)\s*(?=;)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.interface</string>
                    </dict>
                </dict>
            </dict>
            <key>namespace_typename</key>
            <dict>
                <key>match</key>
                <string>(?&lt;=namespace)\s*([\w]+)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>entity.name.type.module</string>
                    </dict>
                </dict>
            </dict>
            <key>parameter</key>
            <dict>
                <key>match</key>
                <string>([\w]+)\s*(?=:|\(|=\s*all|=\s*none|;)</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>variable.other.property</string>
                    </dict>
                </dict>
            </dict>
            <key>interface_targets</key>
            <dict>
                <key>name</key>
                <string>entity.name.tag</string>
                <key>match</key>
                <string>\+[\w]+</string>
            </dict>
            <key>punctuation_terminator</key>
            <dict>
                <key>name</key>
                <string>punctuation.terminator</string>
                <key>match</key>
                <string>;</string>
            </dict>
            <key>punctuation_block</key>
            <dict>
                <key>name</key>
                <string>punctuation.definition.block</string>
                <key>match</key>
                <string>{|}</string>
            </dict>
            <key>punctuation_comma</key>
            <dict>
                <key>name</key>
                <string>punctuation.separator.comma</string>
                <key>match</key>
                <string>,</string>
            </dict>
            <key>punctuation_accessor</key>
            <dict>
                <key>name</key>
                <string>punctuation.accessor</string>
                <key>match</key>
                <string>\.</string>
            </dict>
            <key>operator_assignment</key>
            <dict>
                <key>name</key>
                <string>keyword.operator.assignment</string>
                <key>match</key>
                <string>=</string>
            </dict>
            <key>operator_type_annotation</key>
            <dict>
                <key>name</key>
                <string>keyword.operator.type.annotation</string>
                <key>match</key>
                <string>(-&gt;|:)</string>
            </dict>
            <key>parentheses</key>
            <dict>
                <key>name</key>
                <string>punctuation.definition.parameters</string>
                <key>match</key>
                <string>\(|\)</string>
            </dict>
        </dict>
    </dict>
</plist>
