<?xml version="1.0" encoding="utf-8"?>
<plist version="1.0">
  <dict>
    <key>$schema</key>
    <string>https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json</string>
    <key>name</key>
    <string>PyDjinni</string>
    <key>fileTypes</key>
    <array>
      <string>pydjinni</string>
    </array>
    <key>scopeName</key>
    <string>text.pydjinni</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comment</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#import</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#string</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#typename</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#method</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#property</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#returntype</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constant</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comment</key>
      <dict>
        <key>name</key>
        <string>comment.line.hashtag</string>
        <key>match</key>
        <string>#.*</string>
      </dict>
      <key>string</key>
      <dict>
        <key>match</key>
        <string>".*"</string>
        <key>name</key>
        <string>string.quoted.double</string>
      </dict>
      <key>import</key>
      <dict>
        <key>match</key>
        <string>@import|@extern</string>
        <key>name</key>
        <string>keyword.control.import</string>
      </dict>
      <key>typename</key>
      <dict>
        <key>match</key>
        <string>([a-zA-Z][a-zA-Z0-9_]*) *(=) (interface|enum|record|flags)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>storage.type</string>
          </dict>
        </dict>
      </dict>
      <key>method</key>
      <dict>
        <key>match</key>
        <string>([a-zA-Z][a-zA-Z0-9_]*) *\(</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.function</string>
          </dict>
        </dict>
      </dict>
      <key>property</key>
      <dict>
        <key>match</key>
        <string>([a-zA-Z][a-zA-Z0-9_]*) *(:) *([a-zA-Z][a-zA-Z0-9_]*)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>support.type</string>
          </dict>
        </dict>
      </dict>
      <key>returntype</key>
      <dict>
        <key>match</key>
        <string>(->) *([a-zA-Z][a-zA-Z0-9_]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>support.type</string>
          </dict>
        </dict>
      </dict>
      <key>constant</key>
      <dict>
        <key>match</key>
        <string>([a-zA-Z][a-zA-Z0-9_]*)( *(=) *(all|none))?;</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>variable.other.constant</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.operator</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>support.type</string>
          </dict>
        </dict>
      </dict>
    </dict>
  </dict>
</plist>
